service: searchable-pdf
org: tk_options
frameworkVersion: '3.1.1'

provider:
  name: aws
  stage: dev
  region: eu-west-1
  endpointType: regional
  runtime: java11
  lambdaHashingVersion: 20201221
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 600 # optional, in seconds, default is 6
  environment: # you can define service wide environment variables here
    S3BucketName_TextractJsonFile: tk-options-tobi
    S3Path_TextractJsonFile: src
    S3BucketName_SourcePdf: tk-options-tobi
    S3Path_SourcePdf: src
    S3BucketName_SearchablePdfDestination: tk-options-tobi
    S3Path_SearchablePdfDestination: dest
  iam: # you can add statements to the Lambda function's IAM Role here
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::*/*"
            - "arn:aws:s3:::*"

# you can add packaging information here
package:
  artifact: target/searchable-pdf-1.0.jar

functions:
  searchablePdf:
    handler: com.serverless.Handler
    events:
      - s3:
          existing: true
          bucket: ${self:provider.environment.S3BucketName_TextractJsonFile}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:provider.environment.S3Path_TextractJsonFile}/
            - suffix: .json